# Generated by Django 3.2.13 on 2023-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('auth_code', models.IntegerField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=6)),
                ('activated_invite_code', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
